import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import { HOME, CHAMPION, ITEMLIST, ROTATION } from "@/constant/routePath";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header>
        <nav>
          <Link href={HOME}>홈</Link>
          <Link href={CHAMPION}>챔피언 목록</Link>
          <Link href={ITEMLIST}>아이템 목록</Link>
          <Link href={ROTATION}>챔피언 로테이션</Link>
        </nav>
      </header>
      <body>{children}</body>
      <footer></footer>
    </html>
  );
}
